# Generated by Django 4.1.13 on 2023-11-08 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.cliente'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
